EmployeeSkillProjectAllocationSystem/Controllers/EmployeeController.cs
using EmployeeSkillProjectAllocationSystem.Data;
using EmployeeSkillProjectAllocationSystem.Models;
using EmployeeSkillProjectAllocationSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmployeeSkillProjectAllocationSystem.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _context.Employees
                .Where(e => e.IsActive)
                .Include(e => e.EmployeeSkills)
                .ThenInclude(x => x.skill)
                .Include(e => e.EmployeeProjects)
                .ThenInclude(e => e.Project)
                .ToListAsync();

            return View(result);
        }

        public async Task<IActionResult> Create()
        {
            var EmpVM = new EmployeeCreateViewModel();

            EmpVM.Skills = await _context.Skills
                .Where(x => x.IsActive)
                .Select(x => new SelectListItem {
                    Value = x.Id.ToString(),
                    Text = x.Name
                })
                .ToListAsync();
            return View(EmpVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeCreateViewModel EmpVM)
        {
            if (!ModelState.IsValid)
            {
                return View(EmpVM);
            }
            var employee = new Employee
            {
                Name = EmpVM.Name
            };
            _context.Employees.Add(employee);
            await _context.SaveChangesAsync();

            foreach(var skillId in EmpVM.SelectedSkillId)
            {
                _context.EmployeeSkills.Add(new EmployeeSkill
                {
                    EmployeeId = employee.Id,
                    skillId = skillId
                });
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

EmployeeSkillProjectAllocationSystem/Controllers/ProjectController.cs
using EmployeeSkillProjectAllocationSystem.Data;
using EmployeeSkillProjectAllocationSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace EmployeeSkillProjectAllocationSystem.Controllers
{
    public class ProjectController : Controller
    {
        public readonly ApplicationDbContext _context;

        public ProjectController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var projects = await _context.Projects.OrderBy(x => x.Id).ToListAsync();
            return View(projects);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Project project)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _context.Projects.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Project already exists");
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return View();
            }
            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Project project)
        {
            if(id != project.Id)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View(project);
            }
            _context.Projects.Update(project);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

EmployeeSkillProjectAllocationSystem/Controllers/ProjectTeamController.cs
using EmployeeSkillProjectAllocationSystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmployeeSkillProjectAllocationSystem.Controllers
{
    public class ProjectTeamController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProjectTeamController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var projTeam = _context.Projects
                .Where(x => x.isActive)
                .Include(x => x.EmployeeProjects)
                .ThenInclude(x => x.Employee);
            //var EMP = new EmployeeSkillProjectAllocationSystem.ViewModels.EmployeeProjectViewModel();
            //EMP.Employees = await _context.Employees.Where(x => x.IsActive).Select(x => new SelectListItem
            //{
            //    Value = x.Id.ToString(),
            //    Text = x.Name
            //}).ToListAsync();

            //EMP.Projects = await _context.Projects.Where(x => x.isActive).Select(x => new SelectListItem
            //{
            //    Value = x.Id.ToString(),
            //    Text = x.Name
            //}).ToListAsync();

            //return View(EMP);
            return View(projTeam);
        }
    }
}

EmployeeSkillProjectAllocationSystem/Controllers/SkillController.cs
using EmployeeSkillProjectAllocationSystem.Data;
using EmployeeSkillProjectAllocationSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace EmployeeSkillProjectAllocationSystem.Controllers
{
    [Authorize(Roles = "HR")]
    public class SkillController : Controller
    {
        public readonly ApplicationDbContext _context;
        public SkillController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var skills = await _context.Skills.OrderBy(x => x.Id).ToListAsync();
            return View(skills);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Skill skill)
        {
            if (!ModelState.IsValid)
            {
                return View(skill);
            }
            try
            {
                _context.Skills.Add(skill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Skill already exists");
                return View(skill);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var skill = await _context.Skills.FindAsync(id);
            if (skill == null)
                return NotFound();
            return View(skill);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Skill skill)
        {
            if(id != skill.Id)
                return NotFound();
            if (!ModelState.IsValid)
                return View(skill);

            try
            {
                _context.Skills.Update(skill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Skill already exists");
                return View();
            }
        }
    }
}

EmployeeSkillProjectAllocationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeSkillProjectAllocationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeSkillProjectAllocationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeSkillProjectAllocationSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu">
                                @if(User.Identity.IsAuthenticated && User.IsInRole("HR"))
                                {
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Skill" asp-action="Index">Skills</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Project" asp-action="Index">Projects</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Employee" asp-action="Index">Add Employee</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="ProjectTeam" asp-action="Index">ProjectTeams</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="EmployeeProject" asp-action="Create">Assign Projects</a>
                                    </li>
                                }
                                @if(User.Identity.IsAuthenticated && User.IsInRole("Manager"))
                                {
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Project" asp-action="Index">Projects</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="ProjectTeam" asp-action="Index">ProjectTeams</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                }
                                @if( !User.IsInRole("HR") || !User.IsInRole("Manager"))
                                {
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Employee" asp-action="Index">Employees</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - EmployeeSkillProjectAllocationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_ValidationScriptsPartial" />
</body>
</html>